export const StaffStatus = {
  ACTIVE: "ACTIVE",
  BREAK: "BREAK",
  FIRED: "FIRED",
  BLACKLISTED: "BLACKLISTED",
} as const;
export type StaffStatus = (typeof StaffStatus)[keyof typeof StaffStatus];
export const STAFF_STATUS_VALUES = Object.values(StaffStatus);

export const StaffActivityType = {
  REPORT_CLAIM: "REPORT_CLAIM",
  REPORT_COMPLETE: "REPORT_COMPLETE",
  TICKET_CLAIM: "TICKET_CLAIM",
  TICKET_COMPLETE: "TICKET_COMPLETE",
  GIFT_CLAIM: "GIFT_CLAIM",
  USER_WARNING: "USER_WARNING",
  STAFF_WARNING: "STAFF_WARNING",
  PROMOTE: "PROMOTE",
  DEMOTE: "DEMOTE",
  ACCEPT: "ACCEPT",
  FIRE: "FIRE",
  PUNISHMENT_REQUEST: "PUNISHMENT_REQUEST",
  PUNISHMENT_APPROVED: "PUNISHMENT_APPROVED",
  PUNISHMENT_REJECTED: "PUNISHMENT_REJECTED",
  PUNISHMENT_EXECUTED: "PUNISHMENT_EXECUTED",
  VACATION_REQUEST: "VACATION_REQUEST",
  VACATION_APPROVED: "VACATION_APPROVED",
  VACATION_REJECTED: "VACATION_REJECTED",
  BREAK: "BREAK",
  RETURN_FROM_BREAK: "RETURN_FROM_BREAK",
  APPEAL_CLAIM: "APPEAL_CLAIM",
  APPEAL_ACCEPTED: "APPEAL_ACCEPTED",
  APPEAL_REJECTED: "APPEAL_REJECTED",
  PUNISHMENT_REVOKED: "PUNISHMENT_REVOKED",
  GIFT_CLAIM_REVIEW: "GIFT_CLAIM_REVIEW",
  GIFT_CLAIM_APPROVE: "GIFT_CLAIM_APPROVE",
  GIFT_CLAIM_REJECT: "GIFT_CLAIM_REJECT",
  GIFT_CLAIM_RE_REQUEST: "GIFT_CLAIM_RE_REQUEST",
  GIFT_CLAIM_FULFILL: "GIFT_CLAIM_FULFILL",
  OTHER: "OTHER",
} as const;
export type StaffActivityType = (typeof StaffActivityType)[keyof typeof StaffActivityType];
export const STAFF_ACTIVITY_TYPE_VALUES = Object.values(StaffActivityType);

export const StaffPointTransactionType = {
  REPORT_CLAIM: "REPORT_CLAIM",
  TICKET_CLAIM: "TICKET_CLAIM",
  GIFT_CLAIM: "GIFT_CLAIM",
  USER_WARNING: "USER_WARNING",
  STAFF_WARNING: "STAFF_WARNING",
  APPEAL_SUCCESS_PENALTY: "APPEAL_SUCCESS_PENALTY",
  MANUAL_ADJUSTMENT: "MANUAL_ADJUSTMENT",
  OTHER: "OTHER",
} as const;
export type StaffPointTransactionType =
  (typeof StaffPointTransactionType)[keyof typeof StaffPointTransactionType];
export const STAFF_POINT_TRANSACTION_TYPE_VALUES = Object.values(StaffPointTransactionType);

export const StaffHistoryAction = {
  ACCEPT: "ACCEPT",
  PROMOTE: "PROMOTE",
  DEMOTE: "DEMOTE",
  FIRE: "FIRE",
  BLACKLIST: "BLACKLIST",
  BREAK: "BREAK",
  RETURN_FROM_BREAK: "RETURN_FROM_BREAK",
  STAFF_WARNING: "STAFF_WARNING",
  STAFF_WARNING_REMOVED: "STAFF_WARNING_REMOVED",
  APPEAL_PENALTY: "APPEAL_PENALTY",
  OTHER: "OTHER",
} as const;
export type StaffHistoryAction = (typeof StaffHistoryAction)[keyof typeof StaffHistoryAction];
export const STAFF_HISTORY_ACTION_VALUES = Object.values(StaffHistoryAction);
